# 导入库

In [1]:
# 修改工作路径
import os
from pathlib import Path
os.chdir(Path(os.getcwd()).parent.parent)

In [2]:
os.getcwd()

'D:\\LFProjects\\NewPythonProject'

In [3]:
from data_manager.DailyDataManager import DailyDataManager

# 实例化日线行情数据管理器

日线行情数据位于/data/futures_daily_yyyymmdd_n.pkl，请保持这样的命名方式，yyyymmdd_n表示该日第n个版本，过往版本放到废弃数据文件夹中。

In [4]:
self = DailyDataManager()

# 获取品种列表

In [5]:
self.get_symbol_list()

['A',
 'AG',
 'AL',
 'AP',
 'AU',
 'B',
 'BB',
 'BC',
 'BU',
 'C',
 'CF',
 'CJ',
 'CS',
 'CU',
 'CY',
 'EB',
 'EG',
 'FB',
 'FG',
 'FU',
 'HC',
 'I',
 'IC',
 'IF',
 'IH',
 'J',
 'JD',
 'JM',
 'JR',
 'L',
 'LH',
 'LR',
 'LU',
 'M',
 'MA',
 'NI',
 'NR',
 'OI',
 'P',
 'PB',
 'PF',
 'PG',
 'PK',
 'PM',
 'PP',
 'RB',
 'RI',
 'RM',
 'RR',
 'RS',
 'RU',
 'SA',
 'SC',
 'SF',
 'SM',
 'SN',
 'SP',
 'SR',
 'SS',
 'T',
 'TA',
 'TF',
 'TS',
 'UR',
 'V',
 'WH',
 'WR',
 'WT',
 'Y',
 'ZC',
 'ZN']

# 获取日线行情数据

数据字段：

contract: str, 合约代码\
datetime: datetime, 日期\
high: float, 最高价\
lower_limit: float, 跌停价\
open_interest: float, 持仓量\
close: float, 收盘价\
prev_settlement: float, 前结算价\
low: float, 最低价\
turnover: float, 成交额\
settlement: float, 结算价\
upper_limit: float, 涨停价\
open: float, 开盘价\
volume: float, 成交量\
underlying_symbol: str, 品种代码

In [6]:
daily_data = self.get_daily_data()
daily_data

,contract,datetime,high,lower_limit,open_interest,close,prev_settlement,low,turnover,settlement,upper_limit,open,volume,underlying_symbol
0,A0901,2009-01-05,3736.0,3478.0,2956.0,3660.0,3699.0,3560.0,9168100.0,3696.0,3920.0,3736.0,248.0,A
1,A0901,2009-01-06,3679.0,3475.0,2956.0,3679.0,3696.0,3580.0,2582200.0,3586.0,3917.0,3583.0,72.0,A
2,A0901,2009-01-07,3600.0,3371.0,2956.0,3599.0,3586.0,3599.0,8926300.0,3599.0,3801.0,3600.0,248.0,A
3,A0901,2009-01-08,3600.0,3384.0,2956.0,3600.0,3599.0,3599.0,2591900.0,3599.0,3814.0,3599.0,72.0,A
4,A0901,2009-01-09,3600.0,3384.0,2806.0,3600.0,3599.0,3599.0,1584000.0,3599.0,3814.0,3600.0,44.0,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27043,ZN2202,2021-02-22,21090.0,19820.0,3.0,21090.0,21090.0,21090.0,0.0,21090.0,22355.0,21090.0,0.0,ZN
27044,ZN2202,2021-02-23,21530.0,19820.0,4.0,21165.0,21090.0,21165.0,321100.0,21405.0,22355.0,21530.0,3.0,ZN
27045,ZN2202,2021-02-24,21180.0,20120.0,7.0,21175.0,21405.0,21175.0,317675.0,21175.0,22685.0,21180.0,3.0,ZN
27046,ZN2202,2021-02-25,22045.0,19900.0,5.0,21400.0,21175.0,20910.0,961825.0,21370.0,22445.0,22045.0,9.0,ZN
27047,ZN2202,2021-02-26,21575.0,20085.0,4.0,21575.0,21370.0,21575.0,107875.0,21575.0,22650.0,21575.0,1.0,ZN

# 获取某个品种各合约某个字段的数据


可获取的字段包括:\
high: float, 最高价\
lower_limit: float, 跌停价\
open_interest: float, 持仓量\
close: float, 收盘价\
prev_settlement: float, 前结算价\
low: float, 最低价\
turnover: float, 成交额\
settlement: float, 结算价\
upper_limit: float, 涨停价\
open: float, 开盘价\
volume: float, 成交量\
underlying_symbol: str, 品种代码

In [7]:
self.get_field(symbol='A', field='close')

contract,A0901,A0903,A0905,A0907,A0909,A0911,A1001,A1003,A1005,A1007,...,A2007,A2009,A2011,A2101,A2103,A2105,A2107,A2109,A2111,A2201
datetime,,,,,,,,,,,,,,,,,,,,,
2009-01-05,3660.0,3598.0,3413.0,3308.0,3270.0,3242.0,3213.0,3175.0,3225.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-06,3679.0,3630.0,3459.0,3360.0,3331.0,3305.0,3239.0,3255.0,3240.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-07,3599.0,3610.0,3448.0,3360.0,3307.0,3298.0,3241.0,3292.0,3277.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-08,3600.0,3623.0,3420.0,3348.0,3318.0,3281.0,3263.0,3273.0,3276.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-09,3600.0,3623.0,3462.0,3407.0,3372.0,3340.0,3329.0,3360.0,3340.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5799.0,5878.0,5789.0,5609.0,5527.0,5435.0
2021-02-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5897.0,5937.0,5852.0,5721.0,5535.0,5437.0
2021-02-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5920.0,5985.0,5936.0,5770.0,5555.0,5469.0
2021-02-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5924.0,5989.0,5931.0,5777.0,5584.0,5462.0
2021-02-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5860.0,5873.0,5806.0,5663.0,5598.0,5459.0